services:
  sales-analysis:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sales-analysis

    volumes:
      - ./output:/app/output

    working_dir: /app

    command: python src/main.py

    restart: "no"